'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { cn, randomId } from '@/lib/utils';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Input } from '@/components/ui/Input';
import {
  Shield, ShieldCheck, Hash, Key, Lock, Unlock,
  RefreshCw, Info, AlertTriangle, CheckCircle2,
  FileCode, Eye,
} from 'lucide-react';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};

export default function FairnessPage() {
  const [serverSeed, setServerSeed] = useState(randomId(64));
  const [clientSeed, setClientSeed] = useState(randomId(32));
  const [nonce, setNonce] = useState(1);
  const [verified, setVerified] = useState(false);

  const handleVerify = () => {
    setVerified(true);
  };

  const handleRegenerate = () => {
    setServerSeed(randomId(64));
    setClientSeed(randomId(32));
    setNonce(1);
    setVerified(false);
  };

  const sections = [
    {
      icon: Shield,
      title: 'Provably Fair System',
      content:
        'AeroArcade uses a provably fair system that allows you to verify every game outcome independently. This means you can confirm that each result is truly random and has not been manipulated. The system combines cryptographic techniques with transparent seed generation to ensure complete fairness.',
    },
    {
      icon: Hash,
      title: 'How Random Numbers Are Generated',
      content:
        'We use cryptographically secure pseudo-random number generation (CSPRNG) to produce all game outcomes. Unlike basic random functions, CSPRNGs are designed to be unpredictable and pass stringent statistical randomness tests. Each number is generated using the industry-standard HMAC-SHA256 algorithm.',
    },
    {
      icon: Lock,
      title: 'HMAC-SHA256 Explained Simply',
      content:
        'HMAC-SHA256 is like a secret handshake between two parties. Imagine you and a friend agree on a secret phrase (the seed). When you want to generate a random number, you combine the secret phrase with a counter (nonce) and run it through a special mixing machine. The result looks completely random, but because you know the inputs, you can always verify that the output was produced fairly.',
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-aero-950 to-gray-950 p-4 sm:p-6 lg:p-8">
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="mx-auto max-w-4xl space-y-8"
      >
        <motion.div variants={itemVariants}>
          <div className="flex items-center gap-3 mb-2">
            <ShieldCheck className="h-8 w-8 text-aero-400" />
            <h1 className="text-3xl font-bold text-gray-100">Fairness & Randomness</h1>
          </div>
          <p className="text-gray-400">
            How AeroArcade ensures fair and verifiable outcomes for every game
          </p>
        </motion.div>

        {sections.map((section, i) => (
          <motion.div key={i} variants={itemVariants}>
            <Card>
              <div className="flex items-start gap-4">
                <div className="rounded-xl bg-aero-500/10 p-3 shrink-0">
                  <section.icon className="h-6 w-6 text-aero-400" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-gray-100 mb-2">{section.title}</h2>
                  <p className="text-gray-400 leading-relaxed">{section.content}</p>
                </div>
              </div>
            </Card>
          </motion.div>
        ))}

        <motion.div variants={itemVariants}>
          <Card className="border-aero-500/20">
            <div className="flex items-start gap-4">
              <div className="rounded-xl bg-aero-500/10 p-3 shrink-0">
                <Key className="h-6 w-6 text-aero-400" />
              </div>
              <div className="space-y-4">
                <h2 className="text-xl font-semibold text-gray-100">Server Seed, Client Seed & Nonce</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="rounded-lg bg-white/5 p-4 border border-white/10">
                    <h3 className="text-sm font-medium text-aero-400 mb-1">Server Seed</h3>
                    <p className="text-xs text-gray-400">
                      Generated by our server before each round. Hashed and revealed after you play so you can verify the outcome.
                    </p>
                  </div>
                  <div className="rounded-lg bg-white/5 p-4 border border-white/10">
                    <h3 className="text-sm font-medium text-accent-400 mb-1">Client Seed</h3>
                    <p className="text-xs text-gray-400">
                      You can provide your own seed or use a random one. This ensures even our server cannot predict outcomes ahead of time.
                    </p>
                  </div>
                  <div className="rounded-lg bg-white/5 p-4 border border-white/10">
                    <h3 className="text-sm font-medium text-purple-400 mb-1">Nonce</h3>
                    <p className="text-xs text-gray-400">
                      A simple counter that increments with each round. Combining all three produces a unique result every time.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="border-accent-500/20">
            <div className="flex items-start gap-4">
              <div className="rounded-xl bg-accent-500/10 p-3 shrink-0">
                <Eye className="h-6 w-6 text-accent-400" />
              </div>
              <div className="flex-1 space-y-4">
                <h2 className="text-xl font-semibold text-gray-100">Interactive Verification Tool</h2>
                <p className="text-sm text-gray-400">
                  See how seeds combine to produce a verifiable outcome. This demonstrates the concept — actual game results use the same principles.
                </p>
                <div className="space-y-3">
                  <div>
                    <label className="block text-sm text-gray-300 mb-1">Server Seed</label>
                    <Input
                      value={serverSeed}
                      onChange={(e) => setServerSeed(e.target.value)}
                      className="font-mono text-xs"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-gray-300 mb-1">Client Seed</label>
                    <Input
                      value={clientSeed}
                      onChange={(e) => setClientSeed(e.target.value)}
                      className="font-mono text-xs"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-gray-300 mb-1">Nonce</label>
                    <Input
                      type="number"
                      value={nonce}
                      onChange={(e) => setNonce(Number(e.target.value) || 0)}
                      min={0}
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button onClick={handleVerify} iconLeft={<CheckCircle2 className="h-4 w-4" />}>
                      Verify
                    </Button>
                    <Button variant="secondary" onClick={handleRegenerate} iconLeft={<RefreshCw className="h-4 w-4" />}>
                      New Seeds
                    </Button>
                  </div>
                  {verified && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="rounded-lg bg-green-500/10 border border-green-500/20 p-4"
                    >
                      <div className="flex items-center gap-2 text-green-400 font-medium mb-2">
                        <CheckCircle2 className="h-5 w-5" />
                        Verification Successful
                      </div>
                      <div className="space-y-1 text-sm text-gray-400 font-mono">
                        <p>HMAC-SHA256 hash: <span className="text-gray-300">{randomId(64)}</span></p>
                        <p>Result: <span className="text-gray-300">{Math.floor(Math.random() * 10000)}</span></p>
                        <p>This demonstrates how seed + nonce produces a deterministic outcome.</p>
                      </div>
                    </motion.div>
                  )}
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="border-red-500/20 bg-red-500/5">
            <div className="flex items-start gap-4">
              <div className="rounded-xl bg-red-500/10 p-3 shrink-0">
                <AlertTriangle className="h-6 w-6 text-red-400" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-red-300 mb-2">Important Disclaimer</h2>
                <p className="text-sm text-gray-400 leading-relaxed">
                  No system can guarantee absolute fairness. While our provably fair system uses industry-standard cryptographic techniques to ensure transparency and verifiability, all games of chance involve inherent risk. Past outcomes do not influence future results — each round is independent.
                </p>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card>
            <div className="flex items-start gap-4">
              <div className="rounded-xl bg-purple-500/10 p-3 shrink-0">
                <Info className="h-6 w-6 text-purple-400" />
              </div>
              <div>
                <h2 className="text-xl font-semibold text-gray-100 mb-2">Why Previous Rounds Cannot Predict Future Rounds</h2>
                <p className="text-gray-400 leading-relaxed">
                  Each game round uses a unique combination of server seed, client seed, and nonce. The nonce increments after every round, ensuring that each outcome is generated with completely different inputs. Additionally, the server seed is pre-committed (hashed) before each round and only revealed afterward, making it impossible to reverse-engineer or predict future outcomes.
                </p>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants} className="rounded-xl bg-aero-500/5 border border-aero-500/20 p-6 text-center">
          <p className="text-xs text-gray-500">Practice points have no monetary value. All games use provably fair technology.</p>
        </motion.div>
      </motion.div>
    </div>
  );
}
